### PR TITLE
Release/1.2.0 beta.2

### PR DESCRIPTION
**Pull request by liamegan**
- Added an example of dolly camera and instancing
- Fixed a problem with blend mode setting on a basic program
- Updated the camera object to deal with default destructuting
- Made the program test optional in testing for dept testing - this allows generic objects (groups) to be used without throwing an error

### CODE REVIEW

**Comment by andrewrubin** [comment]
@liamegan I'm getting an error from Vite when trying to run the demo here. That's attached below. Nuked the package lock file locally, as the error message instructed, and that did fix it. Would you be opposed to updating that before we merge?

```
Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Volumes/projects/_repos/wtc/wtc-gl/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (/Volumes/projects/_repos/wtc/wtc-gl/node_modules/rollup/dist/native.js:68:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Volumes/projects/_repos/wtc/wtc-gl/node_modules/rollup/dist/native.js
```

**Comment by liamegan** [comment]
> @liamegan I'm getting an error from Vite when trying to run the demo here. That's attached below. Nuked the package lock file locally, as the error message instructed, and that did fix it. Would you be opposed to updating that before we merge?
> 
> ```
> Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
>     at requireWithFriendlyError (/Volumes/projects/_repos/wtc/wtc-gl/node_modules/rollup/dist/native.js:59:9)
>     at Object.<anonymous> (/Volumes/projects/_repos/wtc/wtc-gl/node_modules/rollup/dist/native.js:68:76)
>     ... 3 lines matching cause stack trace ...
>     at Module._load (node:internal/modules/cjs/loader:1023:12)
>     at cjsLoader (node:internal/modules/esm/translators:345:17)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
>     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
>     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
>   [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
>   Require stack:
>   - /Volumes/projects/_repos/wtc/wtc-gl/node_modules/rollup/dist/native.js
> ```

I can, but what do you need me to update?

**Comment by andrewrubin** [comment]
Sorry that wasn't clear — just need a fresh package json

**Comment by liamegan** [comment]
Done, thanks.

**Comment by andrewrubin** [comment]
It still didn't work for some reason — so I added mine. Probably some mac OS thing

**Review by andrewrubin — APPROVED** [review]
🚀

**Pull request merged**
